name: 01-building-blocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run: echo "Hello Github action world"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo " This is going to fail"
          exit 1
      - name: "Say goodbye"
        run: echo "goodbye ;)"
